// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZwqN_l1xjRj__JjzoY5NuQznH9xYgKiI',
    appId: '1:150555905976:web:16b06a9380ad0be336494d',
    messagingSenderId: '150555905976',
    projectId: 'blog-app-bb537',
    authDomain: 'blog-app-bb537.firebaseapp.com',
    storageBucket: 'blog-app-bb537.appspot.com',
    measurementId: 'G-N5ZHRTMELB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz84zOpaDBmSz7E6rrxqyI8JCR-BSf29s',
    appId: '1:150555905976:android:f27ed9642dc8761b36494d',
    messagingSenderId: '150555905976',
    projectId: 'blog-app-bb537',
    storageBucket: 'blog-app-bb537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfBLBwg8WrznEzkUqwCLil5DOOeLHwx7E',
    appId: '1:150555905976:ios:b7adb752fa5533e836494d',
    messagingSenderId: '150555905976',
    projectId: 'blog-app-bb537',
    storageBucket: 'blog-app-bb537.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfBLBwg8WrznEzkUqwCLil5DOOeLHwx7E',
    appId: '1:150555905976:ios:c3ef5991e9bcc94436494d',
    messagingSenderId: '150555905976',
    projectId: 'blog-app-bb537',
    storageBucket: 'blog-app-bb537.appspot.com',
    iosBundleId: 'com.example.blogApp.RunnerTests',
  );
}
